export const COMMENTS_SET = 'COMMENTS_GET';
export const COMMENTS_CREATE = 'COMMENTS_CREATE';
export const COMMENTS_UPDATE = 'COMMENTS_UPDATE';
export const COMMENTS_DELETE = 'COMMENTS_DELETE';
export const COMMENTS_SORT = 'COMMENTS_SORT';
